### ISSUE TITLE
show PID with chrome tab?

### ISSUE THREAD

**Issue by tazmo** [lemnos/chrome-session-dump#1]
Great tool... been looking for something like this.
Any chance to add a field that shows the process ID/pid associated with the tab?

**Comment by lemnos** [comment]
Unfortunately I do not believe this is possible. Chrome uses session files to reconstruct browsing sessions so the PID is never stored on disk. May I ask what you are trying to achieve?

**Comment by tazmo** [comment]
When looking at top (or htop, bpytop, etc), it would be nice to have a correlation between PID<->tab<->Web Page/site as explained [here](https://stackoverflow.com/questions/39853065/does-chrome-really-create-a-process-for-each-tab). You could tell which web page/site was using more resources than others by name from one of the previously mentioned tools (for example if one web page started consuming an unusual amount of RAM, or CPU, etc). Maybe this exists someplace else...(?)

**Comment by lemnos** [comment]
As you may already be aware, chrome has a built in task manager (shift+esc).  Poking around the source suggests that it uses a custom IPC mechanism called 'mojo' to obtain information from child processes in a platform agnostic way.  It may be possible to tap into this but it would probably be non trivial and quite fragile. I don't believe PIDs are ever stored on disk, but I may be mistaken.

It is probably easier to just resign yourself to treating chrome as the all consuming memory blackbox that it is :P. My own solution to this problem is to keep separate instances open for heavier webapps (e.g chromium --app="https://discord.com/login" --user-data-dir="~/chrome_sessions/discord") and use ublock origin for the rest of my browsing (which is mostly glorified text) but that may not be a viable solution for you.

It may also be possible to implement as an extension, but the relevant API only appears to be available in the dev channel which would require you run a separate version of chrome.
