### ISSUE TITLE
Feature - Build/support on Windows 

### ISSUE THREAD

**Issue by rpurcelldesj** [lemnos/chrome-session-dump#2]
Hi, first thanks for taking the time to build and share this tool with the rest of the world!

I'd like to know if this code could be use "as-is" on windows and if you could provide binaries alongside of macosx and linux ? I'm happy with the Linux build for my desktop but I would be interested on a windows version for other pc I have.

Thanks again!

**Comment by lemnos** [comment]
Sorry for the prolonged response. I believe some of the path logic is UNIX specific but with some minor changes it should be possible to build a working windows binary. Some additional changes to the parsing logic may also be required since chrome seems to store certain values as raw memory dumps which might be represented differently across platforms. I don't have a windows machine up and running at the moment but I will take a look at it when I get some time.

**Comment by rpurcelldesj** [comment]
Allright, thanks for your reply, have a great day!
